### ISSUE TITLE
Values are being quoted with double quotes instead of single quotes

### ISSUE THREAD

**Issue by neb42** [imatic/pgqb#6]
Build a query to select from a table using `WHERE "col" IN (...)` with a list of uuids.
```
import * as qb from '@imatic/pgqb';

const uuid_list = [
  "005f27ae-009b-40f5-8a43-4f4a2186b9f5",
  "89539cad-b7db-45df-8c6b-13609b68a9e2",
  "34dbcf20-afc3-4238-846f-560bcd718c77",
];

const query = qb.toSql(
  qb.merge(
    qb.select(['id']),
    qb.from('my_table'),
    qb.where(qb.expr.in('id', uuid_list)),
  ),
);

console.log(query);
```

The resulting query has the uuids double quoted rather than single quoted. Postgres reads this as columns, not values.
```
SQLStatement {
  strings: [
    `SELECT "id" FROM "my_table" WHERE "id" IN( "005f27ae-009b-40f5-8a43-4f4a2186b9f5", "89539cad-b7db-45df-8c6b-13609b68a9e2", "34dbcf20-afc3-4238-846f-560bcd718c77",)`
  ],
  values: []
}
```

**Comment by nenadalm** [comment]
strings are considered columns, columns are always double quoted. If you want to insert value, you have to wrap it in `qb.val.inlineParam`. See example with `in` here: https://github.com/imatic/pgqb/blob/d7fc32d1c7103c57311ce1fd8d549efbf28345a4/tests/helper_test.ts#L186
